Add Newdumper
pillar-markup/Microdown pull request #304
Opened 2021-11-30 16:02 UTC by lgrangaud

visitors and tests of Dumper

2021-11-30 18:20 UTC, kasperosterbye commented
I can see that you have a lot of failing tests. Most of those tests are in your own tests. 

If you are interested, I can do a discord session with you going through how to make sure your own test are all OK before you push to repository. We are all here to learn to be better software developers.

2021-12-01 08:48 UTC, lgrangaud commented
> I can see that you have a lot of failing tests. Most of those tests are in your own tests.
> 
> If you are interested, I can do a discord session with you going through how to make sure your own test are all OK before you push to repository. We are all here to learn to be better software developers.

Yes, I made a mistake during the PR. So some tests crashed... I will fix it today. If I need help, I will contact you on discord. Thank you for your help

2021-12-01 16:15 UTC, kasperosterbye commented on src/Microdown-RichTextComposer/MicRichTextComposer.class.st
> +		'subscriptColor',
Reintroducing these instance variables in MicRichTextComposer is wrong, they were moved to the TextStyler in one of the earlier pull requests I made. Perhaps you forgot to merge those into your base before pushing?

2021-12-01 16:17 UTC, kasperosterbye commented on src/Microdown/MicCodeBlock.class.st
> +	^ arguments keys isNotEmpty
This works - I think you can simply ask `arguments isNotEmpty`

2021-12-01 16:24 UTC, kasperosterbye requested changes
The reintroduction of the many instance variables into MicRichTextComposer is wrong. They now live in the MicTextStyler class, and if you need them, take them from there, and if you need to add more, add them there.

2021-12-03 11:11 UTC, closed without merging